"""Abstract session protocol for be-conductor.

Both PTY sessions and Agent SDK sessions implement this interface.
Using typing.Protocol (structural typing) so the existing Session
class satisfies it without any inheritance changes.
"""

from __future__ import annotations

import asyncio
from typing import Protocol, Set, runtime_checkable


@runtime_checkable
class SessionProtocol(Protocol):
    """Common interface for all session types."""

    id: str
    name: str
    command: str
    cwd: str | None
    status: str
    session_type: str          # "pty" or "agent"
    pid: int | None
    start_time: float | None
    created_at: str | None
    exit_code: int | None
    rows: int
    cols: int
    resume_id: str | None
    worktree: dict | None
    subscribers: Set[asyncio.Queue]
    resize_source: str | None
    resize_owner_id: str | None
    browser_resize_owner_id: str | None
    cli_attach_count: int

    async def start(self, rows: int = 24, cols: int = 80) -> None: ...
    def send_input(self, text: str) -> None: ...
    def send_input_bytes(self, data: bytes) -> None: ...
    def resize(self, rows: int, cols: int, source: str | None = None,
               client_id: str | None = None) -> None: ...
    def interrupt(self, timeout: float = 30.0) -> None: ...
    async def kill(self) -> None: ...
    async def cleanup(self) -> None: ...
    def subscribe(self) -> asyncio.Queue: ...
    def unsubscribe(self, queue: asyncio.Queue) -> None: ...
    def get_buffer(self) -> bytes: ...
    def get_buffer_text(self, max_lines: int = 500) -> str: ...
    def get_screen_snapshot(self, clean: bool = False) -> bytes: ...
    def to_dict(self) -> dict: ...
    def cli_connected(self, client_id: str) -> None: ...
    def cli_disconnected(self, client_id: str) -> None: ...
    def browser_connected(self, client_id: str, source: str = "browser") -> None: ...
    def browser_disconnected(self, client_id: str) -> None: ...

    @property
    def attached_clients(self) -> list[dict]: ...

    @property
    def live_cwd(self) -> str | None: ...
